### PR TITLE
Laying Down the Foundation for GOG support for Hitman Contracts

### PR DESCRIPTION
**Pull request by Abdulsarhan**
This is a bigger patch this time, so I understand if it takes a while for this to get merged. 
This patch basically lays the foundation for GOG support for Hitman contracts.
I haven't changed any pointers except for the mission time pointer, I fixed the one used for the GOG version, because it was broken. I tested it by temporarily setting the isMissionActive boolean to true, and it worked on the latest GOG version. (v1.74) And I  reverted the boolean back to false before making this PR.
I also tested this patch on the steam version, and everything works on there. I tested it on every level. Even restarted the game a couple times.
Now all we have to do to get this tracker to work on GOG is to just fix all the other pointers. I will fix as many as I can and send them to you as a PR.
If you have a problem with this particular implementation, please let me know.

### CODE REVIEW

**Comment by Abdulsarhan** [comment]
I initially closed it because I thought that there was a lot of code missing. Turns out, github just hides a lot of code that doesn't change in the PR lol.

**Comment by SuiMachine** [comment]
Remind me if I don't check it until Thursday. I should have some time for it tomorrow.

**Comment by Abdulsarhan** [comment]
> Remind me if I don't check it until Thursday. I should have some time for it tomorrow.

👍

**Comment by Abdulsarhan** [comment]
Hey man, it's Friday now. Can you take a look at this PR?

**Comment by SuiMachine** [comment]
Yeah, I forgot. Reminded myself yesterday when I was in bed. I will write it on my whiteboard and have a look at it today after work.

**Comment by SuiMachine** [comment]
Seems there is an issue with detecting mission 😢

**Comment by SuiMachine** [comment]
Even if ignoring that - only time seems to be tracked properly :-/

**Comment by Abdulsarhan** [comment]
> Seems there is an issue with detecting mission 😢

Yeah, like I said, I didn't change any pointers except for the mission time pointer. And that pointer works if you set ismissionactive to true.

**Comment by Abdulsarhan** [comment]
> Even if ignoring that - only time seems to be tracked properly :-/

 Goal of the PR isn't to provide full GOG support, but to lay down the ground work, so that the only thing that needs to be fixed now is pointers.

**Comment by Abdulsarhan** [comment]
But if you want a PR where every pointer works, that's going to take me a lot of time. I am not good at cheat engine.

**Comment by SuiMachine** [comment]
Sure if you want. But I am not going to make builds.

**Comment by Abdulsarhan** [comment]
> Sure if you want. But I am not going to make builds.

Yeah, that's fair.

**Pull request merged**
